{
    "apps": [
        {
            "build_date": "2021-03-04_10:12:58", 
            "changelog": "", 
            "description": "自动部署SSL证书", 
            "home_url": "Module_acme.asp", 
            "md5": "3d94074830ff2e59e8c1d4b8caedbe6a", 
            "name": "acme", 
            "tar_url": "acme/acme.tar.gz", 
            "title": "Let's Encrypt", 
            "version": "3.3"
        }, 
        {
            "build_date": "2021-02-08_21:38:25", 
            "changelog": "", 
            "description": "aliddns", 
            "home_url": "Module_aliddns.asp", 
            "md5": "41cbbab1af121379efe32d207684ae8b", 
            "name": "aliddns", 
            "tar_url": "aliddns/aliddns.tar.gz", 
            "title": "阿里DDNS", 
            "version": "2.1"
        }, 
        {
            "build_date": "2021-02-08_21:38:25", 
            "changelog": "", 
            "description": "linux下载利器", 
            "home_url": "Module_aria2.asp", 
            "md5": "b8cf40dc4ff0f5f0bb7d194979906825", 
            "name": "aria2", 
            "tar_url": "aria2/aria2.tar.gz", 
            "title": "aria2", 
            "version": "2.2"
        }, 
        {
            "build_date": "2021-02-08_21:38:04", 
            "changelog": "", 
            "description": "CloudFlare DDNS", 
            "home_url": "Module_cfddns.asp", 
            "md5": "206451bd74849efe466699776999d4ef", 
            "name": "cfddns", 
            "tar_url": "cfddns/cfddns.tar.gz", 
            "title": "CloudFlare DDNS", 
            "version": "1.0"
        }, 
        {
            "build_date": "2021-02-08_21:38:32", 
            "changelog": "", 
            "description": "ddnspod", 
            "home_url": "Module_ddnspod.asp", 
            "md5": "589a0fcc2f0c4eb5d285b4a474c42206", 
            "name": "ddnspod", 
            "tar_url": "ddnspod/ddnspod.tar.gz", 
            "title": "ddnspod", 
            "version": "1.5"
        }, 
        {
            "build_date": "2021-02-28_23:07:13", 
            "changelog": "", 
            "description": "ddnsto内网穿透", 
            "home_url": "Module_ddnsto.asp", 
            "md5": "785e2561c55536eec88b95964e27ce4a", 
            "name": "ddnsto", 
            "tar_url": "ddnsto/ddnsto.tar.gz", 
            "title": "ddnsto", 
            "version": "2.2"
        }, 
        {
            "build_date": "2021-02-08_21:38:05", 
            "changelog": "", 
            "description": "易有云 （EasyExplorer） 跨平台文件同步，支持双向同步！", 
            "home_url": "Module_easyexplorer.asp", 
            "md5": "e4cc142b47b12a95749928e3d8ba8e5c", 
            "name": "easyexplorer", 
            "tar_url": "easyexplorer/easyexplorer.tar.gz", 
            "title": "易有云", 
            "version": "2.4.1"
        }, 
        {
            "build_date": "2021-02-08_21:38:18", 
            "changelog": "", 
            "description": "迅雷快鸟，上网必备神器", 
            "home_url": "Module_fastd1ck.asp", 
            "md5": "a0e994847a221e51e907d5d216d8cb12", 
            "name": "fastd1ck", 
            "tar_url": "fastd1ck/fastd1ck.tar.gz", 
            "title": "迅雷快鸟", 
            "version": "1.6"
        }, 
        {
            "build_date": "2021-02-08_21:38:06", 
            "changelog": "", 
            "description": "支持多种协议的内网穿透软件", 
            "home_url": "Module_frpc.asp", 
            "md5": "d5561a4be8d00c45ab3ff031b640b4dd", 
            "name": "frpc", 
            "tar_url": "frpc/frpc.tar.gz", 
            "title": "frpc内网穿透", 
            "version": "1.6"
        }, 
        {
            "build_date": "2021-02-08_21:38:11", 
            "changelog": "", 
            "description": "内网穿透利器，谁用谁知道。", 
            "home_url": "Module_frps.asp", 
            "md5": "ed68392768073c648a4fd6e71756b744", 
            "name": "frps", 
            "tar_url": "frps/frps.tar.gz", 
            "title": "frps穿透服务器", 
            "version": "1.5.2"
        }, 
        {
            "build_date": "2021-02-08_21:37:57", 
            "changelog": "", 
            "description": "kms", 
            "home_url": "Module_kms.asp", 
            "md5": "d7c29e3ce50801b5edf7bd7b63cea15e", 
            "name": "kms", 
            "tar_url": "kms/kms.tar.gz", 
            "title": "系统工具", 
            "version": "1.5"
        }, 
        {
            "build_date": "2021-02-08_21:38:30", 
            "changelog": "", 
            "description": "KP: Kids Protect，互联网内容过滤，保护未成年人上网~", 
            "home_url": "Module_koolproxy.asp", 
            "md5": "4106881698b876e60107794472de449b", 
            "name": "koolproxy", 
            "tar_url": "koolproxy/koolproxy.tar.gz", 
            "title": "KidsProtect", 
            "version": "3.8.4.1"
        }, 
        {
            "build_date": "2021-02-08_21:38:18", 
            "changelog": "", 
            "description": "pppoe单线多拨，带宽提升神器！", 
            "home_url": "Module_mdial.asp", 
            "md5": "89bc94d5eafa6d86b0d6be13bd2029a5", 
            "name": "mdial", 
            "tar_url": "mdial/mdial.tar.gz", 
            "title": "单线多拨", 
            "version": "1.3"
        }, 
        {
            "build_date": "2021-03-15_20:43:42", 
            "changelog": "", 
            "description": "通过pushplus将路由器状态推送到微信上", 
            "home_url": "Module_pushplus.asp", 
            "md5": "b82239f5385df4933d7248e60c2f188c", 
            "name": "pushplus", 
            "tar_url": "pushplus/pushplus.tar.gz", 
            "title": "pushplus全能推送", 
            "version": "0.4"
        }, 
        {
            "build_date": "2021-02-08_21:38:17", 
            "changelog": "", 
            "description": "自动签到", 
            "home_url": "Module_qiandao.asp", 
            "md5": "15e3cf138f398f1af9bc9cfd86ef09e8", 
            "name": "qiandao", 
            "tar_url": "qiandao/qiandao.tar.gz", 
            "title": "自动签到", 
            "version": "1.5"
        }, 
        {
            "build_date": "2021-02-08_21:38:31", 
            "changelog": "", 
            "description": "解决重启Bug", 
            "home_url": "Module_reboothelper.asp", 
            "md5": "fdbc8129a961153c984e2ed99e610fa2", 
            "name": "reboothelper", 
            "tar_url": "reboothelper/reboothelper.tar.gz", 
            "title": "重启助手", 
            "version": "0.6"
        }, 
        {
            "build_date": "2021-03-12_14:32:52", 
            "changelog": "", 
            "description": "一些小功能的插件", 
            "home_url": "Module_rog.asp", 
            "md5": "490a571fc13367c628d63a64b8c62b84", 
            "name": "rog", 
            "tar_url": "rog/rog.tar.gz", 
            "title": "ROG工具箱", 
            "version": "4.2"
        }, 
        {
            "build_date": "2021-02-08_21:38:13", 
            "changelog": "", 
            "description": "从路由器推送状态及通知的工具", 
            "home_url": "Module_routerhook.asp", 
            "md5": "c7452cc34ad646625dc7232672bf6ffe", 
            "name": "routerhook", 
            "tar_url": "routerhook/routerhook.tar.gz", 
            "title": "RouterHook事件回调", 
            "version": "1.2"
        }, 
        {
            "build_date": "2021-02-08_21:37:56", 
            "changelog": "", 
            "description": "从路由器推送状态及通知的工具", 
            "home_url": "Module_serverchan.asp", 
            "md5": "8be8abbefbbc9d37ed4dbf467481eec1", 
            "name": "serverchan", 
            "tar_url": "serverchan/serverchan.tar.gz", 
            "title": "serverChan微信推送", 
            "version": "1.4.1"
        }, 
        {
            "build_date": "2021-02-08_21:37:57", 
            "changelog": "", 
            "description": "超强的SSH网页客户端~", 
            "home_url": "Module_shellinabox.asp", 
            "md5": "c570797e4dd1b66c58c13d280a9c5ece", 
            "name": "shellinabox", 
            "tar_url": "shellinabox/shellinabox.tar.gz", 
            "title": "shellinabox", 
            "version": "1.5"
        }, 
        {
            "build_date": "2021-02-08_21:37:57", 
            "changelog": "", 
            "description": "上海电信IPTV，4K IPTV 一键开启", 
            "home_url": "Module_shiptv.asp", 
            "md5": "c715aaf790fb30e4e83055e1c6eff5cb", 
            "name": "shiptv", 
            "tar_url": "shiptv/shiptv.tar.gz", 
            "title": "上海电信IPTV", 
            "version": "1.1"
        }, 
        {
            "build_date": "2021-02-08_21:37:58", 
            "changelog": "", 
            "description": "VPN全家桶, ver 4.29 build 9680", 
            "home_url": "Module_softether.asp", 
            "md5": "ca4a04729535013d873aee6d21ff6089", 
            "name": "softether", 
            "tar_url": "softether/softether.tar.gz", 
            "title": "SoftEther_VPN_Server", 
            "version": "1.9"
        }, 
        {
            "build_date": "2021-03-04_11:54:18", 
            "changelog": "", 
            "description": "让路由器运行更稳定~", 
            "home_url": "Module_swap.asp", 
            "md5": "90bcf4efb96ca8e5679432b69a310572", 
            "name": "swap", 
            "tar_url": "swap/swap.tar.gz", 
            "title": "虚拟内存", 
            "version": "2.6"
        }, 
        {
            "build_date": "2021-04-01_14:42:40", 
            "changelog": "", 
            "description": "使用U盘轻松挂载jffs", 
            "home_url": "Module_usb2jffs.asp", 
            "md5": "da5204b4e2a6c452e924e0e06f77b76a", 
            "name": "usb2jffs", 
            "tar_url": "usb2jffs/usb2jffs.tar.gz", 
            "title": "USB2JFFS", 
            "version": "1.9.4"
        }, 
        {
            "build_date": "2021-02-28_21:16:54", 
            "changelog": "", 
            "description": "wifi boost: 路由器WiFi功率增强，增加信号覆盖范围。", 
            "home_url": "Module_wifiboost.asp", 
            "md5": "81d5823b32e6f9eba197b29fce820155", 
            "name": "wifiboost", 
            "port": "8083", 
            "server": "42.192.18.234", 
            "tar_url": "wifiboost/wifiboost.tar.gz", 
            "title": "wifi boost", 
            "version": "3.9"
        }, 
        {
            "build_date": "2021-04-01_21:17:34", 
            "changelog": "", 
            "description": "ZeroTier 内网穿透", 
            "home_url": "Module_zerotier.asp", 
            "md5": "cfa5813a6ec8c9e511a9df8dd1baf1e9", 
            "name": "zerotier", 
            "tar_url": "zerotier/zerotier.tar.gz", 
            "title": "ZeroTier", 
            "version": "1.3.5"
        }
    ], 
    "home_url": "https://raw.githubusercontent.com/koolshare/koolshare.github.io/master", 
    "md5": "73f760a04c89b0bd735dfda7a1838c66", 
    "tar_url": "softcenter/softcenter.tar.gz", 
    "version": "1.6.9"
}